version: "3.7"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb_data: /var/lib/mysql
    restart: always
    env_file: .env

network: inception