version: "3.7"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    restart: always
    env_file: .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - inception

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    restart: always
    depends_on:
      - wordpress
    env_file: .env
    networks:
      - inception

volumes:
  marivol:
    name: marivol
    driver: local
    driver_opts:
      type: none
      device: /home/palucena/data/mariadb
      o: bind
      
  wpvol:
    name: wpvol
    driver: local
    driver_opts:
      type: none
      device: /home/palucena/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge