version: "3.7"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    restart: always
    env_file: .env
    ports:
      - 3306
    networks:
      - inception
  
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file: .env
    ports:
      - 9000
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge