services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - marivol:/var/lib/mysql
    env_file: .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    volumes:
      - wpvol:/var/www
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - inception

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    restart: always
    volumes:
      - wpvol:/var/www
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "12443:12443"
    networks:
      - inception

volumes:
  marivol:
    name: marivol
    driver: local
    driver_opts:
      type: none
      device: /home/palucena/data/mariadb
      o: bind
      
  wpvol:
    name: wpvol
    driver: local
    driver_opts:
      type: none
      device: /home/palucena/data/html
      o: bind

networks:
  inception:
    driver: bridge